version: '3.8'

networks:
  web:
    driver: bridge

services:
  fooddelivery-backend:
    container_name: fooddelivery-backend
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - fooddeliverydb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fooddeliverydb:5432/fooddeliverydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=sa
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    networks:
      - web

  fooddelivery-order-logger:
    container_name: fooddelivery-order-logger_container
    image: fooddelivery-order-logger:latest
    environment:
       - SPRING_DATA_MONGODB_URI=mongodb://orderloggerdb:27017/orderloggerdb
       - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    ports:
      - "8081:8081"
    depends_on:
      - orderloggerdb
    networks:
      - web

  fooddeliverydb:
    image: postgres:14.9
    container_name: fooddeliverydb
    environment:
      - POSTGRES_DB=fooddeliverydb
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-sa}
#      - PGDATA=/data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db-data:/data/postgres
    restart: unless-stopped
    networks:
      - web

  orderloggerdb:
    image: mongo:latest
    container_name: orderloggerdb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=orderloggerdb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db-data:/data/mongo
    networks:
      - web

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7.3
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    networks:
      - web

  eureka-server:
    image: fooddelivery-eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - web
    environment:
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
