version: '3.8'

networks:
  web:
    driver: bridge

services:
  fooddelivery-backend:
#    image: fooddelivery-backend:1.0
    container_name: fooddelivery
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - fooddeliverydb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fooddeliverydb:5432/fooddeliverydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=sa
#      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
    networks:
      - web

  fooddeliverydb:
    image: postgres:14.9
    container_name: fooddeliverydb
    environment:
      - POSTGRES_DB=fooddeliverydb
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-sa}
      - PGDATA=/data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db-data:/data/postgres
    restart: unless-stopped
    networks:
      - web

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:7.3
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin1@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    networks:
      - web

#volumes:
#  db-data:
#  pgadmin-data: