server:
  port: 8080
  servlet:
    context-path: /fooddelivery

spring:
  liquibase:
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: sa
    url: jdbc:postgresql://localhost:5432/fooddeliverydb

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
    format-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

  main:
    allow-circular-references: true
  thymeleaf:
    check-template-location: false
  application:
    name: fooddelivery

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
jwt:
  lifetime: 10m

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  exchange:
    name: amq.direct
  queue:
    json:
      name: order
  routing:
    json:
      key: order
