jwt:
  lifetime: 10m
server:
  port: 8080
  servlet:
    context-path: /fooddelivery
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: fooddeliverysch
    password: sa
    url: jdbc:postgresql://localhost:5432/fooddeliverydb
    username: postgres
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    format-sql: true
    hibernate:
      ddl-auto: validate
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    show-sql: true
  main:
    allow-circular-references: true
  thymeleaf:
    check-template-location: false
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
